# A versão é obsoleta, então a removemos para limpar os avisos.
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - frontend_build:/usr/share/nginx/html
      - ./backend/uploads:/usr/share/nginx/html/uploads
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  backend:
    build: ./backend
    image: ${DOCKER_USERNAME:-default_user}/backend:latest
    # CORREÇÃO AQUI: A seção 'environment' precisa ser um mapa de chave-valor.
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./backend/uploads:/app/uploads
    ports:
      - "5000:5000"
    command: sh -c "./wait-for.sh db 3306 && npm start"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    image: lpn2025-frontend-image
    volumes:
      - frontend_build:/app/build

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/config/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  frontend_build:
  db_data:
    # Protege o volume do banco de dados contra exclusão acidental
    external: true
