version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend  # Espera o backend estar pronto
      - frontend  # Espera o frontend estar pronto

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c '
      if [ ! -f /etc/letsencrypt/live/ligapaulistadenatacao.com.br/fullchain.pem ]; then
        certbot certonly --webroot -w /var/www/certbot --agree-tos -n --email jhonattanwcs@hotmail.com -d ligapaulistadenatacao.com.br -d www.ligapaulistadenatacao.com.br;
      fi;
      while :; do certbot renew; sleep 12h; done;'

  backend:
    image: ${DOCKER_USERNAME:-default_user}/backend:latest
    build:
      context: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3306
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: sh -c "./wait-for.sh db:3306 -- npm start"  # Corrigido para passar host e porta
    depends_on:
      - db

  frontend:
    image: ${DOCKER_USERNAME:-default_user}/frontend:latest
    build:
      context: ./frontend
      target: production  # Especifica o estágio de produção
    volumes:
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  frontend_build: