version: '3.8'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/backend:latest
    build:
      context: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ${CERTIFICATES_PATH}:/certificados
    depends_on:
      - db

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
    build:
      context: ./frontend
      target: production  # Usa o estágio production do Dockerfile
    command: ["sh", "-c", "cd /usr/share/nginx/html && npx serve -s ."]  # Serve os arquivos estáticos
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Certificados SSL
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"

volumes:
  db_data: