version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      API_URL: ${API_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "5000:5000"
    volumes:
      - ${CERTIFICATES_PATH}:/certificados
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CERTIFICATES_PATH}:/etc/letsencrypt/live/localhost
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done;'"

volumes:
  db_data: