services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:3000"
    command: npm start

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt


  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
