name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Login no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build e Push do Backend
    - name: Build and Push Backend
      run: |
        docker build -t lpn/backend:latest ./backend
        docker push lpn/backend:latest

    # 4. Build e Push do Frontend
    - name: Build and Push Frontend
      run: |
        docker build -t lpn/frontend:latest ./frontend
        docker push lpn/frontend:latest

    # 5. Deploy no Servidor
    - name: Deploy to Production
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker-compose --version || sudo apt-get install -y docker-compose
          cd /home/user/project
          docker-compose down || true
          docker-compose pull
          docker-compose up -d
