name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Verificar o conteúdo do diretório de trabalho
      - name: Verify workspace directory
        run: ls -la ${{ github.workspace }}

      # 3. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4. Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build e Push do Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend:latest

      # 6. Build e Push do Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # 7. Sincronizar arquivos com o servidor
      - name: Sincronizar Repositorio com sercvidor
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
          mkdir -p /var/www/lpn2025
          ls -la /github/workspace  # Verificar permissões
          rsync -avz --delete $GITHUB_WORKSPACE/ /var/www/lpn2025/


      # 8. Deploy no Servidor
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker-compose --version || sudo apt-get install -y docker-compose-plugin
            cd /var/www/lpn2025
            docker-compose down || true
            docker-compose pull
            docker-compose up -d --no-deps backend frontend